allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - postcss@8.5.16
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - sharp
  - unrs-resolver
  - "@tailwindcss/oxide"
